apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: student-pvc
spec:
  storageClassName: ""   # empty = don't use default storageclass, bind to my PV
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
