apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-web
  namespace: session20
  labels:
    app: gitops-web
spec:
  replicas: 3   # changed in git -> argo should scale it, no kubectl needed
  selector:
    matchLabels:
      app: gitops-web
  template:
    metadata:
      labels:
        app: gitops-web
    spec:
      containers:
        - name: web
          image: nginx:1.27-alpine
          ports:
            - containerPort: 80
