apiVersion: v1
kind: Pod
metadata:
  name: fail-3-pending-pod
spec:
  containers:
    - name: hungry-app
      image: nginx:alpine
      resources:
        requests:
          cpu: "100m"     # was 500 cores
          memory: "64Mi"  # was 1000Gi
